# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20180514_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='demo_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
