# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20180514_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='demo_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
