# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20180514_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='demo',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='details',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
