# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20180514_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='details',
        ),
    ]
