# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_remove_enquiry_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='soft_ava',
            new_name='existing_software',
        ),
    ]
